### PR TITLE
WIP skip-initial-eor work

### PR DESCRIPTION
**Pull request by charlescng**
WIP

* [x] rename 'skip-initial-eor' to 'manual-eor' (or 'manually-send-eor' ?)
* [x] ~~make it an option with 'never', 'initial' and 'always' ( if you have better idea for the names feel free to come with options :wink: )~~
* [x] ~~change the code in the main loop to send it if not set to always~~
* [x] make sure the Neighbor class when printed does include the option
* [ ] add the right .group and .sequence file for your configuration file (will require an helper script for this)

### CODE REVIEW

**Comment by charlescng** [comment]
@thomas-mangin, thanks for the comments. I have a few questions:

> make it an option with 'never', 'initial' and 'always'

What's the use case for 'always'?

> change the code in the main loop to send it if not set to always

Why is this needed and where should it be done?

> add the right .group and .sequence file for your configuration file (will require an helper script for this)

The `.group` file just points to the `.conf` file? How do I generate the `.sequence` file?

**Comment by thomas-mangin** [comment]
Sorry, I commented too quickly, a boolean is indeed enough for 'manual-eor'

**Comment by thomas-mangin** [comment]
The sequence file contains the content of the packets the peer is expecting to see.
The best way is to just use our dummy bgp server ( ./qa/sbin/bgp ) and connect exabgp to it using the '-d' option which will then print the packets generated.

**Comment by charlescng** [comment]
Thanks. I'll give it a go. :smile: 

I don't have to modify the main loop, correct?

**Comment by thomas-mangin** [comment]
correct, not AFAICS.

**Comment by charlescng** [comment]
:+1:

**Pull request closed without merging**
